import assert from 'node:assert/strict';
import test from 'node:test';
import { hashAlertToken, signUnsubscribeToken } from '../../.test-dist/lib/alerts-core.js';
import { ALERT_CONSENT_SOURCE, ALERT_CONSENT_TEXT, buildPublicAlertEmail, confirmAlertSubscription, prepareApprovedPublicAlertDelivery, requestAlertSubscription, sendClaimedAlert, unsubscribeFromAlerts, validatedSiteUrl } from '../../.test-dist/lib/alerts-workflow.js';

const NOW = new Date('2026-08-06T12:00:00.000Z');
const KEY = 'synthetic-alert-signing-key-00000000000000000000';
const PREVIOUS_KEY = 'synthetic-previous-signing-key-000000000000000';
const CONFIRMATION = 'synthetic_confirmation_token_000000000000000000';
const UNSUB_ID = 'synthetic_unsubscribe_identifier_00000000000000';
const accepted = { ok: true, skipped: false, providerMessageId: 'synthetic_provider_1' };

function record(overrides={}) { return { id:'synthetic-subscriber-1', email_normalized:'synthetic@example.test', status:'pending', confirmation_token_hash:null, confirmation_expires_at:null, unsubscribe_token_id:UNSUB_ID, unsubscribe_token_version:1, preferences:{categories:['all_public_alerts']}, confirmation_last_sent_at:null, confirmation_window_started_at:null, confirmation_send_count:0, ...overrides }; }
class MemoryStore {
  constructor(rows=[]) { this.rows=rows; this.pendingInputs=[]; this.sentMarks=[]; this.deliveries=new Map(); this.deliveryUpdates=[]; this.writes=0; }
  async findSubscriberByEmail(email) { return this.rows.find((row)=>row.email_normalized===email) ?? null; }
  async savePending(input) { this.writes++; this.pendingInputs.push(structuredClone(input)); let row=await this.findSubscriberByEmail(input.email); if(!row){ row=record({id:`synthetic-${this.rows.length+1}`,email_normalized:input.email,unsubscribe_token_id:input.unsubscribeTokenId}); this.rows.push(row); } Object.assign(row,{status:'pending',confirmation_token_hash:input.confirmationTokenHash,confirmation_expires_at:input.confirmationExpiresAt,confirmation_window_started_at:input.windowStartedAt,confirmation_send_count:input.sendCount}); return row; }
  async markConfirmationSent(id,at) { this.writes++; this.sentMarks.push({id,at}); const row=this.rows.find((item)=>item.id===id); if(row) row.confirmation_last_sent_at=at; }
  async activateByConfirmationHash(hash,now) { const row=this.rows.find((item)=>item.status==='pending'&&item.confirmation_token_hash===hash&&Date.parse(item.confirmation_expires_at)>now.getTime()); if(!row)return null; this.writes++; row.status='active'; row.confirmation_token_hash=null; row.confirmation_expires_at=null; return {id:row.id,email_normalized:row.email_normalized}; }
  async unsubscribeByTokenId(id) { const row=this.rows.find((item)=>item.unsubscribe_token_id===id&&['pending','active'].includes(item.status)); if(row){this.writes++;row.status='unsubscribed';return true;} return false; }
  async activeSubscribers() { return this.rows; }
  async claimDelivery({subscriberId,alertEventKey}) { const key=`${subscriberId}:${alertEventKey}`; if(this.deliveries.has(key))return null; const value={id:`delivery-${this.deliveries.size+1}`,subscriber_id:subscriberId,alert_event_key:alertEventKey,delivery_status:'queued'}; this.deliveries.set(key,value); return value; }
  async updateDelivery(id,status,details={}) { const row=[...this.deliveries.values()].find((item)=>item.id===id); if(row&&row.delivery_status!=='sent')Object.assign(row,{delivery_status:status,...details}); this.deliveryUpdates.push({id,status,...details}); }
}
function deps(store, result=accepted, now=NOW) { const sent=[]; return { sent, value:{now:()=>now,siteUrl:'https://mmips.com',confirmationFactory:()=>({token:CONFIRMATION,hash:hashAlertToken(CONFIRMATION),expiresAt:new Date(now.getTime()+48*3600000).toISOString()}),unsubscribeIdFactory:()=>UNSUB_ID,signingKeys:[KEY],mailer:{async send(message){sent.push(structuredClone(message));return typeof result==='function'?result(message):result;}}}, store }; }

test('new subscription stores normalized pending consent and hashes but no raw bearer credentials', async()=>{ const store=new MemoryStore(), d=deps(store); const result=await requestAlertSubscription(store,'  SYNTHETIC@EXAMPLE.TEST ',{},d.value); assert.deepEqual(result,{ok:true,code:'accepted'}); const input=store.pendingInputs[0]; assert.equal(input.email,'synthetic@example.test'); assert.equal(input.consentSource,ALERT_CONSENT_SOURCE); assert.equal(input.consentText,ALERT_CONSENT_TEXT); assert.equal(input.requestedAt,NOW.toISOString()); assert.equal(input.confirmationTokenHash,hashAlertToken(CONFIRMATION)); assert.equal(JSON.stringify(input).includes(CONFIRMATION),false); assert.equal(input.unsubscribeTokenId,UNSUB_ID); assert.equal(JSON.stringify(input).includes(signUnsubscribeToken(UNSUB_ID,KEY)),false); assert.equal(store.rows[0].status,'pending'); assert.equal(store.sentMarks.length,1); assert.equal(d.sent.length,1); });
test('provider unavailable, rejected and retryable failures do not record successful-send timestamp', async()=>{ for(const code of ['provider_unconfigured','provider_rejected','provider_unavailable']){ const store=new MemoryStore(), d=deps(store,{ok:false,skipped:code==='provider_unconfigured',code}); assert.deepEqual(await requestAlertSubscription(store,'synthetic@example.test',{},d.value),{ok:true,code:'accepted'}); assert.equal(store.sentMarks.length,0); assert.equal(store.pendingInputs[0].sendCount,1); } });
test('cooldown, normalization and daily window prevent repeated mail while post-cooldown advances count', async()=>{ const recent=record({confirmation_last_sent_at:new Date(NOW.getTime()-60_000).toISOString(),confirmation_window_started_at:new Date(NOW.getTime()-3600000).toISOString(),confirmation_send_count:1}), store=new MemoryStore([recent]), d=deps(store); await requestAlertSubscription(store,' SYNTHETIC@EXAMPLE.TEST ',{},d.value); assert.equal(d.sent.length,0); assert.equal(store.pendingInputs.length,0); recent.confirmation_last_sent_at=new Date(NOW.getTime()-11*60_000).toISOString(); await requestAlertSubscription(store,'synthetic@example.test',{},d.value); assert.equal(d.sent.length,1); assert.equal(store.pendingInputs[0].sendCount,2); recent.confirmation_last_sent_at=new Date(NOW.getTime()-11*60_000).toISOString(); recent.confirmation_send_count=3; await requestAlertSubscription(store,'synthetic@example.test',{},d.value); assert.equal(d.sent.length,1); });
test('active and suppressed requests are generic and do not send; unsubscribed explicitly resubscribes preserving id', async()=>{ for(const status of ['active','suppressed']){const store=new MemoryStore([record({status})]),d=deps(store);assert.deepEqual(await requestAlertSubscription(store,'synthetic@example.test',{},d.value),{ok:true,code:'accepted'});assert.equal(d.sent.length,0);} const store=new MemoryStore([record({status:'unsubscribed'})]),d=deps(store);assert.deepEqual(await requestAlertSubscription(store,'synthetic@example.test',{},d.value),{ok:true,code:'accepted'});assert.equal(store.rows[0].status,'pending');assert.equal(store.pendingInputs[0].unsubscribeTokenId,UNSUB_ID); });
test('all valid states are non-enumerating while invalid email is correctable', async()=>{ for(const status of ['pending','active','unsubscribed','suppressed']){const row=record({status,confirmation_last_sent_at:NOW.toISOString()}),d=deps(new MemoryStore([row]));assert.deepEqual(await requestAlertSubscription(d.store,'synthetic@example.test',{},d.value),{ok:true,code:'accepted'});} const d=deps(new MemoryStore());assert.deepEqual(await requestAlertSubscription(d.store,'invalid',{},d.value),{ok:false,code:'invalid_email'}); });
test('atomic synthetic confirmation permits one concurrent success email and generic responses', async()=>{ const row=record({confirmation_token_hash:hashAlertToken(CONFIRMATION),confirmation_expires_at:new Date(NOW.getTime()+1000).toISOString()}),store=new MemoryStore([row]),d=deps(store); const results=await Promise.all([confirmAlertSubscription(store,CONFIRMATION,d.value),confirmAlertSubscription(store,CONFIRMATION,d.value)]); assert.deepEqual(results,[{ok:true,code:'confirmation_processed'},{ok:true,code:'confirmation_processed'}]); assert.equal(d.sent.length,1); assert.equal(row.status,'active'); assert.deepEqual(await confirmAlertSubscription(store,'invalid',d.value),{ok:true,code:'confirmation_processed'}); });
test('expired and already-used confirmations are generic and send no success email', async()=>{ for(const row of [record({confirmation_token_hash:hashAlertToken(CONFIRMATION),confirmation_expires_at:new Date(NOW.getTime()-1).toISOString()}),record({status:'active',confirmation_token_hash:null})]){const store=new MemoryStore([row]),d=deps(store);assert.deepEqual(await confirmAlertSubscription(store,CONFIRMATION,d.value),{ok:true,code:'confirmation_processed'});assert.equal(d.sent.length,0);} });
test('signed unsubscribe supports current/previous keys, pending/active idempotency, and ignores invalid/suppressed', async()=>{ for(const status of ['pending','active']){const row=record({status}),store=new MemoryStore([row]),d=deps(store);const token=signUnsubscribeToken(UNSUB_ID,KEY);assert.deepEqual(await unsubscribeFromAlerts(store,token,d.value),{ok:true,code:'unsubscribe_processed'});assert.equal(row.status,'unsubscribed');assert.deepEqual(await unsubscribeFromAlerts(store,token,d.value),{ok:true,code:'unsubscribe_processed'});} const previous=record({status:'active'}),store=new MemoryStore([previous]),d=deps(store);d.value.signingKeys=[KEY,PREVIOUS_KEY];await unsubscribeFromAlerts(store,signUnsubscribeToken(UNSUB_ID,PREVIOUS_KEY),d.value);assert.equal(previous.status,'unsubscribed'); for(const token of ['malformed',signUnsubscribeToken(UNSUB_ID,PREVIOUS_KEY)]){const protectedRow=record({status:'suppressed'}),s=new MemoryStore([protectedRow]),x=deps(s);await unsubscribeFromAlerts(s,token,x.value);assert.equal(protectedRow.status,'suppressed');} });
test('delivery preparation filters unsafe events and inactive statuses and ledger blocks duplicates', async()=>{ const rows=['active','pending','unsubscribed','suppressed'].map((status,index)=>record({id:`synthetic-${index}`,status})),store=new MemoryStore(rows),base={key:'synthetic-event',kind:'new_public_profile',title:'Synthetic public update',publicUrl:'https://mmips.com/cases/synthetic',approved:true,published:true}; for(const changes of [{approved:false},{published:false},{hidden:true},{removed:true}])assert.equal((await prepareApprovedPublicAlertDelivery(store,{...base,...changes})).queued,0); assert.equal((await prepareApprovedPublicAlertDelivery(store,base)).queued,1); assert.equal((await prepareApprovedPublicAlertDelivery(store,base)).queued,0); assert.equal(store.deliveries.size,1); });
test('delivery state follows provider acceptance, retryable failure, and final rejection without duplicate claims', async()=>{ for(const [result,status] of [[accepted,'sent'],[{ok:false,skipped:false,code:'provider_unavailable'},'failed_retryable'],[{ok:false,skipped:false,code:'provider_rejected'},'failed_final']]){const store=new MemoryStore(),claim=await store.claimDelivery({subscriberId:'synthetic-1',alertEventKey:`event-${status}`});await sendClaimedAlert(store,claim,{to:'synthetic@example.test',subject:'safe',text:'safe',html:'<p>safe</p>'},{send:async()=>result});assert.equal(store.deliveryUpdates[0].status,status);} });
test('public alert output has safe headers, visible signed links, no tracking, and non-personal idempotency',()=>{ const message=buildPublicAlertEmail({title:'Synthetic approved update',publicUrl:'https://mmips.com/cases/synthetic',unsubscribeTokenId:UNSUB_ID,signingKey:KEY,deliveryKey:'private-delivery-1',siteUrl:'https://mmips.com'}); assert.match(message.headers['List-Unsubscribe'],/^<https:\/\/mmips\.com\/api\/alerts\/unsubscribe\?token=v1\./); assert.equal(message.headers['List-Unsubscribe-Post'],'List-Unsubscribe=One-Click'); assert.ok(message.text.includes(message.unsubscribeUrl)); assert.ok(message.html.includes(escapeForHtml(message.unsubscribeUrl))); assert.equal(/pixel|<img/i.test(message.html),false); assert.equal(message.idempotencyKey.includes('synthetic@example.test'),false); });
function escapeForHtml(value){return value.replaceAll('&','&amp;').replaceAll("'",'&#039;');}
test('public URL and site configuration reject foreign, HTTP, credentialed, and non-profile URLs',()=>{ for(const publicUrl of ['http://mmips.com/cases/synthetic','https://foreign.example/cases/synthetic','https://mmips.com/private/synthetic'])assert.throws(()=>buildPublicAlertEmail({title:'Synthetic',publicUrl,unsubscribeTokenId:UNSUB_ID,signingKey:KEY,deliveryKey:'delivery',siteUrl:'https://mmips.com'})); for(const site of ['http://mmips.com','not-a-url','https://user:pass@mmips.com'])assert.throws(()=>validatedSiteUrl(site)); });
